main: nl.parrotlync.discovoutlines.DiscovOutlines
name: ${artifactId}
version: ${version}
api-version: 1.15.2
description: ${description}
depend: [HolographicDisplays]
author: ParrotLync
commands:
  outlines:
    description: Main DiscovOutlines command
    usage: /outlines
    aliases: [o]
permissions:
  discovoutlines.use:
    default: op
    description: Use DiscovOutlines