main: nl.parrotlync.discovoutlines.DiscovOutlines
name: DiscovOutlines
version: 1.1
description: Outlines plugin for the Discovery Network
depend: [HolographicDisplays]
author: ParrotLync
commands:
  outlines:
    description: Main DiscovOutlines command
    usage: /outlines
    aliases: [o]
permissions:
  discovoutlines.use:
    default: op
    description: Use DiscovOutlines